path: E:\repositorio\OIDv4_ToolKit\OID\Dataset\train\Human body
train: E:\repositorio\OIDv4_ToolKit\OID\Dataset\train\Human body\Image_train
val: E:\repositorio\OIDv4_ToolKit\OID\Dataset\train\Human body\Image_train

#classes

names: 
  0: Human body